wiki/plugins/attachments/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from wiki.plugins.attachments import views

urlpatterns = [
    url(r'^$',
        views.AttachmentView.as_view(),
        name='attachments_index'),
    url(r'^search/$',
        views.AttachmentSearchView.as_view(),
        name='attachments_search'),
    url(r'^add/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentAddView.as_view(),
        name='attachments_add'),
    url(r'^replace/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentReplaceView.as_view(),
        name='attachments_replace'),
    url(r'^history/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentHistoryView.as_view(),
        name='attachments_history'),
    url(r'^download/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentDownloadView.as_view(),
        name='attachments_download'),
    url(r'^delete/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentDeleteView.as_view(),
        name='attachments_delete'),
    url(r'^download/(?P<attachment_id>[0-9]+)/revision/(?P<revision_id>[0-9]+)/$',
        views.AttachmentDownloadView.as_view(),
        name='attachments_download'),
    url(r'^change/(?P<attachment_id>[0-9]+)/revision/(?P<revision_id>[0-9]+)/$',
        views.AttachmentChangeRevisionView.as_view(),
        name='attachments_revision_change'),
]

wiki/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, url
from wiki.conf import settings
from wiki.core.plugins import registry
from wiki.core.plugins.loader import load_wiki_plugins
from wiki.core.utils import get_class_from_str
from wiki.views import accounts, article, deleted_list


class WikiURLPatterns(object):

    '''
    configurator for wiki urls.

    To customize, you can define your own subclass, either overriding
    the view providers, or overriding the functions that collect
    views.
    '''

    # basic views
    article_view_class = article.ArticleView
    article_create_view_class = article.Create
    article_delete_view_class = article.Delete
    article_deleted_view_class = article.Deleted
    article_dir_view_class = article.Dir
    article_edit_view_class = article.Edit
    article_move_view_class = article.Move
    article_preview_view_class = article.Preview
    article_history_view_class = article.History
    article_settings_view_class = article.Settings
    article_source_view_class = article.Source
    article_plugin_view_class = article.Plugin
    revision_change_view_class = article.ChangeRevisionView
    revision_merge_view = staticmethod(article.merge)

    search_view_class = settings.SEARCH_VIEW
    article_diff_view = staticmethod(article.diff)

    # account views
    signup_view_class = accounts.Signup
    login_view_class = accounts.Login
    logout_view_class = accounts.Logout
    profile_update_view_class = accounts.Update

    # deleted list view
    deleted_list_view_class = deleted_list.DeletedListView

    def get_urls(self):
        urlpatterns = self.get_root_urls()
        urlpatterns += self.get_accounts_urls()
        urlpatterns += self.get_deleted_list_urls()
        urlpatterns += self.get_revision_urls()
        urlpatterns += self.get_article_urls()
        urlpatterns += self.get_plugin_urls()

        # This ALWAYS has to be the last of all the patterns since
        # the paths in theory could wrongly match other targets.
        urlpatterns += self.get_article_path_urls()
        return urlpatterns

    def get_root_urls(self):
        urlpatterns = [
            url(r'^$',
                self.article_view_class.as_view(),
                name='root',
                kwargs={'path': ''}),
            url(r'^create-root/$',
                article.CreateRootView.as_view(),
                name='root_create'),
            url(r'^missing-root/$',
                article.MissingRootView.as_view(),
                name='root_missing'),
            url(r'^_search/$',
                get_class_from_str(self.search_view_class).as_view(),
                name='search'),
            url(r'^_revision/diff/(?P<revision_id>[0-9]+)/$',
                self.article_diff_view,
                name='diff'),
        ]
        return urlpatterns

    def get_deleted_list_urls(self):
        urlpatterns = [
            url('^_admin/$',
                self.deleted_list_view_class.as_view(),
                name="deleted_list"),
        ]
        return urlpatterns

    def get_accounts_urls(self):
        if settings.ACCOUNT_HANDLING:
            urlpatterns = [
                url(r'^_accounts/sign-up/$',
                    self.signup_view_class.as_view(),
                    name='signup'),
                url(r'^_accounts/logout/$',
                    self.logout_view_class.as_view(),
                    name='logout'),
                url(r'^_accounts/login/$',
                    self.login_view_class.as_view(),
                    name='login'),
                url(r'^_accounts/settings/$',
                    self.profile_update_view_class.as_view(),
                    name='profile_update'),
            ]
        else:
            urlpatterns = []
        return urlpatterns

    def get_revision_urls(self):
        urlpatterns = [
            # This one doesn't work because it don't know
            # where to redirect after...
            url(
                r'^_revision/change/(?P<article_id>[0-9]+)/(?P<revision_id>[0-9]+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(r'^_revision/preview/(?P<article_id>[0-9]+)/$',
                self.article_preview_view_class.as_view(),
                name='preview_revision'),
            url(
                r'^_revision/merge/(?P<article_id>[0-9]+)/(?P<revision_id>[0-9]+)/preview/$',
                self.revision_merge_view,
                name='merge_revision_preview',
                kwargs={
                    'preview': True}),
        ]
        return urlpatterns

    def get_article_urls(self):
        urlpatterns = [
            # Paths decided by article_ids
            url(r'^(?P<article_id>[0-9]+)/$',
                self.article_view_class.as_view(),
                name='get'),
            url(r'^(?P<article_id>[0-9]+)/delete/$',
                self.article_delete_view_class.as_view(),
                name='delete'),
            url(r'^(?P<article_id>[0-9]+)/deleted/$',
                self.article_deleted_view_class.as_view(),
                name='deleted'),
            url(r'^(?P<article_id>[0-9]+)/edit/$',
                self.article_edit_view_class.as_view(),
                name='edit'),
            url(r'^(?P<article_id>[0-9]+)/move/$',
                self.article_move_view_class.as_view(),
                name='move'),
            url(r'^(?P<article_id>[0-9]+)/preview/$',
                self.article_preview_view_class.as_view(),
                name='preview'),
            url(r'^(?P<article_id>[0-9]+)/history/$',
                self.article_history_view_class.as_view(),
                name='history'),
            url(r'^(?P<article_id>[0-9]+)/settings/$',
                self.article_settings_view_class.as_view(),
                name='settings'),
            url(r'^(?P<article_id>[0-9]+)/source/$',
                self.article_source_view_class.as_view(),
                name='source'),
            url(
                r'^(?P<article_id>[0-9]+)/revision/change/(?P<revision_id>[0-9]+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(
                r'^(?P<article_id>[0-9]+)/revision/merge/(?P<revision_id>[0-9]+)/$',
                self.revision_merge_view,
                name='merge_revision'),
            url(r'^(?P<article_id>[0-9]+)/plugin/(?P<slug>\w+)/$',
                self.article_plugin_view_class.as_view(),
                name='plugin'),
        ]
        return urlpatterns

    def get_article_path_urls(self):
        urlpatterns = [
            # Paths decided by URLs
            url(r'^(?P<path>.+/|)_create/$',
                self.article_create_view_class.as_view(),
                name='create'),
            url(r'^(?P<path>.+/|)_delete/$',
                self.article_delete_view_class.as_view(),
                name='delete'),
            url(r'^(?P<path>.+/|)_deleted/$',
                self.article_deleted_view_class.as_view(),
                name='deleted'),
            url(r'^(?P<path>.+/|)_edit/$',
                self.article_edit_view_class.as_view(),
                name='edit'),
            url(r'^(?P<path>.+/|)_move/$',
                self.article_move_view_class.as_view(),
                name='move'),
            url(r'^(?P<path>.+/|)_preview/$',
                self.article_preview_view_class.as_view(),
                name='preview'),
            url(r'^(?P<path>.+/|)_history/$',
                self.article_history_view_class.as_view(),
                name='history'),
            url(r'^(?P<path>.+/|)_dir/$',
                self.article_dir_view_class.as_view(),
                name='dir'),
            url(r'^(?P<path>.+/|)_search/$',
                get_class_from_str(self.search_view_class).as_view(),
                name='search'),
            url(r'^(?P<path>.+/|)_settings/$',
                self.article_settings_view_class.as_view(),
                name='settings'),
            url(r'^(?P<path>.+/|)_source/$',
                self.article_source_view_class.as_view(),
                name='source'),
            url(
                r'^(?P<path>.+/|)_revision/change/(?P<revision_id>[0-9]+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(
                r'^(?P<path>.+/|)_revision/merge/(?P<revision_id>[0-9]+)/$',
                self.revision_merge_view,
                name='merge_revision'),
            url(r'^(?P<path>.+/|)_plugin/(?P<slug>\w+)/$',
                self.article_plugin_view_class.as_view(),
                name='plugin'),
            # This should always go last!
            url(r'^(?P<path>.+/|)$',
                self.article_view_class.as_view(),
                name='get'),
        ]
        return urlpatterns

    @staticmethod
    def get_plugin_urls():
        urlpatterns = []
        for plugin in registry.get_plugins().values():
            slug = getattr(plugin, 'slug', None)
            if slug:
                article_urlpatterns = plugin.urlpatterns.get('article', [])
                urlpatterns += [
                    url(r'^(?P<article_id>[0-9]+)/plugin/' + slug + '/',
                        include(article_urlpatterns)),
                    url(r'^(?P<path>.+/|)_plugin/' + slug + '/',
                        include(article_urlpatterns)),
                ]
                root_urlpatterns = plugin.urlpatterns.get('root', [])
                urlpatterns += [
                    url(r'^_plugin/' + slug + '/', include(root_urlpatterns)),
                ]
        return urlpatterns


def get_pattern(app_name="wiki", namespace="wiki", url_config_class=None):
    """Every url resolution takes place as "wiki:view_name".
       You should not attempt to have multiple deployments of the wiki in a
       single Django project.

wiki/views/deleted_list.py
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from wiki import models


class DeletedListView(TemplateView):

    template_name = "wiki/deleted_list.html"

    def dispatch(self, request, *args, **kwargs):
        # Let logged in super users continue
        if not request.user.is_superuser:
            return redirect('wiki:root')

        return super(DeletedListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        article_list = models.Article.objects.all()
        deleted_articles = []
        for article in article_list:
            if(article.current_revision.deleted):
                deleted_articles.append(article)
        kwargs['deleted_articles'] = deleted_articles
        return super(DeletedListView, self).get_context_data(**kwargs)

wiki/templates/wiki/article.html
{% extends "wiki/base.html" %}
{% load wiki_tags i18n sekizai_tags %}


{% block wiki_pagetitle %}{{ article.current_revision.title }}{% endblock %}

{% block wiki_breadcrumbs %}
{% include "wiki/includes/breadcrumbs.html" %}
{% endblock %}

{% block wiki_contents %}

  <div id="article-container">
    <ul class="nav nav-pills" id="article-menu">
      <li class="pull-left" id="article-title-li">
        <h1 id="article-title">
          {{ article.current_revision.title }}
          <small style="font-size: 14px;">
            {% if urlpath.parent %}
            <a href="{% url 'wiki:get' path=urlpath.path %}"><span class="fa fa-bookmark"></span> {{ urlpath.slug }}</a>
            {% endif %}
            {% if article.current_revision.locked %}
              <span class="fa fa-lock"></span> {% trans "locked" %}
            {% endif %}
          </small>
        </h1>
      </li>
      {% include "wiki/includes/article_menu.html" %}
    </ul>
    <div>
      {% block wiki_contents_tab %}
      {% endblock %}
    </div>
  </div>

{% endblock %}

{% block wiki_footer_prepend %}
  <p style="margin-bottom: 10px;"><em>{% trans "This article was last modified:" %} {{ article.current_revision.modified }}</em></p>
{% endblock %}

wiki/templates/wiki/base.html
{% extends "wiki/base_site.html" %}

{# Intentionally empty, to allow easy customization with no copy-paste #}

wiki/templates/wiki/create.html
{% extends "wiki/base.html" %}
{% load wiki_tags i18n sekizai_tags static %}


{% block wiki_pagetitle %}{% trans "Add new article" %}{% endblock %}

{% block wiki_contents %}

  {% addtoblock "js" %}
  <script type="text/javascript" src="{% static "admin/js/urlify.js" %}"></script>
  <script type="text/javascript">
  {% if not create_form.slug.value %}
  //<![CDATA[
  (function($) {
	  $(document).ready(function (){
		  $("#id_title").keyup(function () {
			  var e = $("#id_slug")[0];
			  if(!e._changed) {
			    slug = URLify(this.value, 50);
				  e.value = slug;
			  }
	      });
	  });
  })(jQuery);
  //]]>
  {% endif %}
  </script>
  {% endaddtoblock %}

  {% include "wiki/includes/editormedia.html" %}
  <h1 class="page-header">{% trans "Add new article" %}</h1>

  <form method="POST" class="form-horizontal">
    {% wiki_form create_form %}
    <div class="form-group form-actions">
      <div class="col-lg-2"></div>
      <div class="col-lg-10">
        <a href="{% url 'wiki:get' path=parent_urlpath.path %}" class="btn btn-default">
          <span class="fa fa-arrow-left"></span>
          {% trans "Go back" %}
        </a>
        <button type="submit" name="save_changes" class="btn btn-primary">
          <span class="fa fa-plus"></span>
          {% trans "Create article" %}
        </button>
      </div>
    </div>
  </form>

{% endblock %}

wiki/templates/wiki/delete.html
{% extends "wiki/base.html" %}
{% load wiki_tags i18n sekizai_tags %}


{% block wiki_pagetitle %}{% trans "Delete article" %}{% endblock %}

{% block wiki_contents %}
  <h1 class="page-header">{% trans "Delete" %} "{{ article.current_revision.title }}"</h1>

  {% if cannot_delete_root %}
    <p class="lead">{% trans "You cannot delete a root article." %}</p>
    <p><a href="{% url 'wiki:get' path=urlpath.path article_id=article.id %}">{% trans "Go back" %}</a></p>
  {% else %}

    {% if cannot_delete_children %}

      <p class="alert alert-danger"><strong>{% trans "You cannot delete this article because you do not have permission to delete articles with children. Try to remove the children manually one-by-one." %}</strong></p>

    {% endif %}

    {% if delete_children %}

      <p class="lead">{% trans "You are deleting an article. This means that its children will be deleted as well. If you choose to purge, children will also be purged!" %}</p>

      <h2>{% trans "Articles that will be deleted" %}</h2>

      <ul>
        {% for child in delete_children %}
        <li><a href="{% url 'wiki:get' article_id=child.article.id %}" target="_blank">{{ child.article }}</a></li>
        {% if delete_children_more %}
        <li><em>{% trans "...and more!" %}</em></li>
        {% endif %}
        {% endfor %}
      </ul>

    {% endif %}

    {% if not cannot_delete_children %}
    <p class="lead">{% trans "You are deleting an article. Please confirm." %}</p>

    <form method="POST" class="form-horizontal">
      {% wiki_form delete_form %}
      <div class="form-group form-actions">
        <div class="col-lg-2"></div>
        <div class="col-lg-10">
          <a href="{% url 'wiki:get' path=urlpath.path article_id=article.id %}" class="btn btn-default">
            <span class="fa fa-arrow-left"></span>
            {% trans "Go back" %}
          </a>
          <button type="submit" name="save_changes" class="btn btn-danger">
            <span class="fa fa-trash-o"></span>
            {% trans "Delete article" %}
          </button>
        </div>
      </div>
    </form>
    {% endif %}

  {% endif %}

{% addtoblock "js" %}
<script type="text/javascript">
  $('#id_revision').val('{{ article.current_revision.id }}');
</script>
{% endaddtoblock %}

{% endblock %}

wiki/templates/wiki/deleted_list.html
{% extends "wiki/base.html" %}
{% load i18n wiki_tags sekizai_tags %}

{% block wiki_pagetitle %}{% trans "Admin Panel" %}{% endblock %}

{% block wiki_contents %}

<h1 class="page-header">{% trans "Deleted Articles" %}</h1>
{% if deleted_articles %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>{% trans "Page Title" %}</th>
        <th>{% trans "Date Deleted" %}</th>
        <th>{% trans "Restore Article" %}</th>
      </tr>
    </thead>
    <tbody>
    {% for article in deleted_articles %}
      <tr>
        <td><a href="{{article.get_absolute_url}}">{{ article }}</a></td>
        <td> {{article.modified}} </td>
        <td><a href="{% url 'wiki:deleted' article_id=article.id %}?restore=1" class="btn btn-default"><span class="fa fa-repeat"></span>
            {% trans "Restore" %}</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <b> {% trans "No deleted articles to display" %} </b>
{% endif %}

{% endblock %}

wiki/templates/wiki/dir.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}


{% block wiki_pagetitle %}{% trans "Listing articles in" %} {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% url 'wiki:dir' urlpath.path as self_url %}

<form class="form-search directory-toolbar">
<div class="well well-small">
  <div class="btn-group pull-left">
    {% if urlpath.parent %}
    <a href="{% url 'wiki:dir' path=urlpath.parent.path %}" class="btn btn-default">
      <span class="fa fa-arrow-up"></span>
      {% trans "Up one level" %}
    </a>
    {% endif %}
    <a href="{% url 'wiki:create' path=urlpath.path %}" class="btn btn-default">
      <span class="fa fa-plus"></span>
      {% trans "Add article" %}
    </a>
  </div>
  <div class="pull-right">
    {{ filter_form.query }}
  </div>
  {% if filter_query %}
    <div class="pull-right filter-clear">
      <a href="{{ self_url }}">({% trans "clear" %})</a>
    </div>
  {% endif %}

  <div class="clearfix"></div>
</div>
</form>

<p>
  {% with paginator.object_list.count as cnt %}
    {% blocktrans with urlpath.path as path and cnt|pluralize:_("article,articles") as articles_plur and cnt|pluralize:_("is,are") as articles_plur_verb %}
      Browsing <strong><a href="{{ self_url }}">/{{ path }}</a></strong>. There {{ articles_plur_verb }} <strong>{{ cnt }} {{ articles_plur }}</strong> in this level.
    {% endblocktrans %}
  {% endwith %}
</p>

<table class="table table-striped">
  <tr>
    <th>{% trans "Title" %}</th>
    <th>{% trans "Slug" %}</th>
    <th>{% trans "Last modified" %}</th>
  </tr>
  {% for urlpath in directory %}
    <tr>
      <td>
        <a href="{% url 'wiki:get' path=urlpath.path %}"> {{ urlpath.article.current_revision.title }} </a>
        <a href="{% url 'wiki:dir' path=urlpath.path %}" class="list-children"> › </a>
        {% if urlpath.article.current_revision.deleted %}
          <span class="fa fa-trash"></span>
        {% endif %}
        {% if urlpath.article.current_revision.locked %}
          <span class="fa fa-lock"></span>
        {% endif %}
      </td>
      <td>
        {{ urlpath.slug }}
      </td>
      <td>
        {{ urlpath.article.current_revision.created|naturaltime }}
      </td>
    </tr>
    {% empty%}
    <tr>
      <td colspan="100">
        <em>{% trans "There are no articles in this level" %}</em>
      </td>
    </tr>
  {% endfor %}
</table>

{% include "wiki/includes/pagination.html" %}

{% endblock %}

wiki/templates/wiki/edit.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n sekizai_tags %}


{% block wiki_pagetitle %}{% trans "Edit" %}: {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% if not user.is_authenticated %}
<p class="alert alert-warning">
{% trans "<strong>Warning:</strong> You are not logged in. Your IP address will be logged." %}
<a href="{% url 'wiki:login' %}?next={% url 'wiki:edit' article_id=article.id path=urlpath.path %}">{% trans "Click here to log in" %} &raquo;</a>
</p>
{% endif %}

<div class="row">

  <div class="col-lg-8">
    <form method="POST" class="form-horizontal" id="article_edit_form">
      {% with edit_form as form %}
        {% include "wiki/includes/editor.html" %}
      {% endwith %}

      <div class="form-group form-actions">
        <div class="col-lg-12">
          <div class="col-lg-offset-2">
            <button class="btn btn-default" type="submit" name="preview" value="1" id="id_preview"
                    formaction="{% url 'wiki:preview' path=urlpath.path article_id=article.id %}"
                    formtarget="previewWindow"
                    >
              <span class="fa fa-eye"></span>
              {% trans "Preview" %}
            </button>
            <button class="btn btn-primary" type="submit" name="save" value="1" id="id_save">
              <span class="fa fa-check"></span>
              {% trans "Save changes" %}
            </button>

            <div class="btn-toolbar pull-right">
              {% if user.is_authenticated and urlpath.path %}
              <a href="{% url 'wiki:move' path=urlpath.path article_id=article.id %}" class="btn btn-warning ">
                <span class="fa fa-random"></span>
                {% trans "Move article" %}
              </a>
              {% endif %}
              {% if article|can_delete:user %}
              <a href="{% url 'wiki:delete' path=urlpath.path article_id=article.id %}" class="btn btn-danger">
                <span class="fa fa-trash-o"></span>
                {% trans "Delete article" %}
              </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>

    </form>
  </div>

  <div class="col-lg-4" id="wiki-edit-sidebar">
    {% include "wiki/includes/editor_sidebar.html" %}
  </div>

</div>

<div style="clear: both"></div>

{% include "wiki/includes/modals.html" %}

<div class="modal fade wiki-modal" id="previewModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <iframe name="previewWindow" frameborder="0"></iframe>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-default btn-lg" data-dismiss="modal">
          <span class="fa fa-arrow-circle-left"></span>
          {% trans "Back to editor" %}
        </a>
        <a class="btn btn-lg btn-primary" id="id_preview_save_changes" href="#">
          <span class="fa fa-check"></span>
          {% trans "Save changes" %}
        </a>
      </div>
    </div>
  </div>
</div>

{% addtoblock "js" %}
<script language="javascript">
  $(document).ready(function() {
    $("#article_edit_form :input").change(function() {
       $("#article_edit_form").data("changed",true);
    });
    if ($("#article_edit_form").find(".alert-danger").length > 0 || $("#article_edit_form").find(".has-error").length > 0 ) {
      // Set the forms status as "changed" if there was a submission error
      $("#article_edit_form").data("changed",true);
    }
    window.onbeforeunload = confirmOnPageExit;
    var click_time = 0;
    $("#article_edit_form").on("submit", function (ev) {
        now = Date.now();
        elapsed = now-click_time;
        click_time = now;
        if (elapsed < 3000)
            ev.preventDefault();
        window.onbeforeunload = null;
        return true;
    });
    $("#id_preview").on("click", function () {
        $("#previewModal").modal("show");
        return true;
    });
    $("#id_preview_save_changes").on("click", function (ev) {
        ev.preventDefault();
        $("#id_save").trigger("click");
    });
  });

var confirmOnPageExit = function (e) {
  if ($("#article_edit_form").data("changed")) {
    e = e || window.event;
    var message = "You have unsaved changes!";
    // For IE6-8 and Firefox prior to version 4
    if (e) {
        e.returnValue = message;
    }
    // For Chrome, Safari, IE8+ and Opera 12+
    return message;
  } else {
    // If the form hasn't been changed, don't display the pop-up
    return;
  }
};
</script>
{% endaddtoblock %}

{% endblock %}

wiki/templates/wiki/error.html
{% extends "wiki/base.html" %}
{% load wiki_tags i18n %}


{% block wiki_pagetitle %}{% if article %}{{ article.current_revision.title }}{% else %}{% trans "Error" %}{% endif %}{% endblock %}

{% block wiki_breadcrumbs %}
{% include "wiki/includes/breadcrumbs.html" %}
{% endblock %}

{% block wiki_contents %}

{% if error_type == "ancestors_missing" %}

  <h1 class="page-header">{% trans "Not found" %}</h1>

  <div class="missing">
    <p>{% trans "This article was not found, and neither was its parent article." %}</p>
    <p>
      <a href="{% url 'wiki:get' path='' %}" class="btn btn-default"><i class="fa fa-arrow-left"></i> {% trans "Start page" %}</a>
    </p>
  </div>

{% else %}

  <h1 class="page-header">{% trans "Error" %}</h1>

  <div class="error">
    {% if not error_msg %}
    <p>{% trans "There was some sort of error accessing this page. Sorry!" %}</p>
    {% else %}
    <p>{{ error_msg }}</p>
    {% endif %}
  </div>

  {% if article %}
  <p>
    <a href="{% url 'wiki:get' path=urlpath.path article_id=article.id %}" class="btn btn-default"><i class="fa fa-arrow-left"></i> {% trans "Back to" %} {{ article.current_revision.title }}</a>
  </p>
  {% endif %}


{% endif %}

{% endblock %}

wiki/templates/wiki/root_missing.html
{% extends "wiki/create_root.html" %}
{% load i18n wiki_tags %}

{% block wiki_contents %}

<div class="row">
  <div class="col-lg-2"></div>
  <div class="col-lg-8">

    <h1>{% trans "Congratulations!" %}</h1>
    <p class="lead">
      {% trans "You have django-wiki installed and it seems to be working. But there are no articles yet." %}
    </p>

    {% if not user.is_superuser %}
      <p class="lead">
        {% trans "Not to worry! You simply have to login with a superuser account and create the first article in the root of the URL hierarchy." %}
      </p>
      {% login_url as wiki_login_url %}
      {% if wiki_login_url %}
        <a href="{{ wiki_login_url }}" class="btn btn-primary btn-lg">{% trans "Click here to login" %}</a>
      {% endif %}

    {% else %}

      <p class="lead">
        {% trans "But since you're logged in as a superuser, we should really get started..." %}
      </p>
      <a href="{% url 'wiki:root_create' %}" class="btn btn-primary btn-lg">{% trans "Yes, I'll go and create the first article" %}</a>
      <a href="http://django-wiki.readthedocs.org/" class="btn btn-default">{% trans "No thanks, I'd rather read the documentation" %}</a>

      {% endif %}
  </div>
  <div class="col-lg-2"></div>
</div>

{% endblock %}

wiki/templates/wiki/source.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}


{% block wiki_pagetitle %}{% trans "Source of" %} {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% if article.current_revision.locked %}
<p class="lead">{% trans "This article is currently locked for editing." %}</p>
{% endif %}

<pre class="pre-scrollable">
  {{ article.current_revision.content }}
</pre>

{% endblock %}

wiki/templates/wiki/view.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n sekizai_tags %}


{% block wiki_contents_tab %}

  {% wiki_render article %}

{% endblock %}