wiki/plugins/attachments/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from wiki.plugins.attachments import views

urlpatterns = [
    url(r'^$',
        views.AttachmentView.as_view(),
        name='attachments_index'),
    url(r'^search/$',
        views.AttachmentSearchView.as_view(),
        name='attachments_search'),
    url(r'^add/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentAddView.as_view(),
        name='attachments_add'),
    url(r'^replace/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentReplaceView.as_view(),
        name='attachments_replace'),
    url(r'^history/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentHistoryView.as_view(),
        name='attachments_history'),
    url(r'^download/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentDownloadView.as_view(),
        name='attachments_download'),
    url(r'^delete/(?P<attachment_id>[0-9]+)/$',
        views.AttachmentDeleteView.as_view(),
        name='attachments_delete'),
    url(r'^download/(?P<attachment_id>[0-9]+)/revision/(?P<revision_id>[0-9]+)/$',
        views.AttachmentDownloadView.as_view(),
        name='attachments_download'),
    url(r'^change/(?P<attachment_id>[0-9]+)/revision/(?P<revision_id>[0-9]+)/$',
        views.AttachmentChangeRevisionView.as_view(),
        name='attachments_revision_change'),
]

wiki/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, url
from wiki.conf import settings
from wiki.core.plugins import registry
from wiki.core.plugins.loader import load_wiki_plugins
from wiki.core.utils import get_class_from_str
from wiki.views import accounts, article, deleted_list


class WikiURLPatterns(object):

    '''
    configurator for wiki urls.

    To customize, you can define your own subclass, either overriding
    the view providers, or overriding the functions that collect
    views.
    '''

    # basic views
    article_view_class = article.ArticleView
    article_create_view_class = article.Create
    article_delete_view_class = article.Delete
    article_deleted_view_class = article.Deleted
    article_dir_view_class = article.Dir
    article_edit_view_class = article.Edit
    article_move_view_class = article.Move
    article_preview_view_class = article.Preview
    article_history_view_class = article.History
    article_settings_view_class = article.Settings
    article_source_view_class = article.Source
    article_plugin_view_class = article.Plugin
    revision_change_view_class = article.ChangeRevisionView
    revision_merge_view = staticmethod(article.merge)

    search_view_class = settings.SEARCH_VIEW
    article_diff_view = staticmethod(article.diff)

    # account views
    signup_view_class = accounts.Signup
    login_view_class = accounts.Login
    logout_view_class = accounts.Logout
    profile_update_view_class = accounts.Update

    # deleted list view
    deleted_list_view_class = deleted_list.DeletedListView

    def get_urls(self):
        urlpatterns = self.get_root_urls()
        urlpatterns += self.get_accounts_urls()
        urlpatterns += self.get_deleted_list_urls()
        urlpatterns += self.get_revision_urls()
        urlpatterns += self.get_article_urls()
        urlpatterns += self.get_plugin_urls()

        # This ALWAYS has to be the last of all the patterns since
        # the paths in theory could wrongly match other targets.
        urlpatterns += self.get_article_path_urls()
        return urlpatterns

    def get_root_urls(self):
        urlpatterns = [
            url(r'^$',
                self.article_view_class.as_view(),
                name='root',
                kwargs={'path': ''}),
            url(r'^create-root/$',
                article.CreateRootView.as_view(),
                name='root_create'),
            url(r'^missing-root/$',
                article.MissingRootView.as_view(),
                name='root_missing'),
            url(r'^_search/$',
                get_class_from_str(self.search_view_class).as_view(),
                name='search'),
            url(r'^_revision/diff/(?P<revision_id>[0-9]+)/$',
                self.article_diff_view,
                name='diff'),
        ]
        return urlpatterns

    def get_deleted_list_urls(self):
        urlpatterns = [
            url('^_admin/$',
                self.deleted_list_view_class.as_view(),
                name="deleted_list"),
        ]
        return urlpatterns

    def get_accounts_urls(self):
        if settings.ACCOUNT_HANDLING:
            urlpatterns = [
                url(r'^_accounts/sign-up/$',
                    self.signup_view_class.as_view(),
                    name='signup'),
                url(r'^_accounts/logout/$',
                    self.logout_view_class.as_view(),
                    name='logout'),
                url(r'^_accounts/login/$',
                    self.login_view_class.as_view(),
                    name='login'),
                url(r'^_accounts/settings/$',
                    self.profile_update_view_class.as_view(),
                    name='profile_update'),
            ]
        else:
            urlpatterns = []
        return urlpatterns

    def get_revision_urls(self):
        urlpatterns = [
            # This one doesn't work because it don't know
            # where to redirect after...
            url(
                r'^_revision/change/(?P<article_id>[0-9]+)/(?P<revision_id>[0-9]+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(r'^_revision/preview/(?P<article_id>[0-9]+)/$',
                self.article_preview_view_class.as_view(),
                name='preview_revision'),
            url(
                r'^_revision/merge/(?P<article_id>[0-9]+)/(?P<revision_id>[0-9]+)/preview/$',
                self.revision_merge_view,
                name='merge_revision_preview',
                kwargs={
                    'preview': True}),
        ]
        return urlpatterns

    def get_article_urls(self):
        urlpatterns = [
            # Paths decided by article_ids
            url(r'^(?P<article_id>[0-9]+)/$',
                self.article_view_class.as_view(),
                name='get'),
            url(r'^(?P<article_id>[0-9]+)/delete/$',
                self.article_delete_view_class.as_view(),
                name='delete'),
            url(r'^(?P<article_id>[0-9]+)/deleted/$',
                self.article_deleted_view_class.as_view(),
                name='deleted'),
            url(r'^(?P<article_id>[0-9]+)/edit/$',
                self.article_edit_view_class.as_view(),
                name='edit'),
            url(r'^(?P<article_id>[0-9]+)/move/$',
                self.article_move_view_class.as_view(),
                name='move'),
            url(r'^(?P<article_id>[0-9]+)/preview/$',
                self.article_preview_view_class.as_view(),
                name='preview'),
            url(r'^(?P<article_id>[0-9]+)/history/$',
                self.article_history_view_class.as_view(),
                name='history'),
            url(r'^(?P<article_id>[0-9]+)/settings/$',
                self.article_settings_view_class.as_view(),
                name='settings'),
            url(r'^(?P<article_id>[0-9]+)/source/$',
                self.article_source_view_class.as_view(),
                name='source'),
            url(
                r'^(?P<article_id>[0-9]+)/revision/change/(?P<revision_id>[0-9]+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(
                r'^(?P<article_id>[0-9]+)/revision/merge/(?P<revision_id>[0-9]+)/$',
                self.revision_merge_view,
                name='merge_revision'),
            url(r'^(?P<article_id>[0-9]+)/plugin/(?P<slug>\w+)/$',
                self.article_plugin_view_class.as_view(),
                name='plugin'),
        ]
        return urlpatterns

    def get_article_path_urls(self):
        urlpatterns = [
            # Paths decided by URLs
            url(r'^(?P<path>.+/|)_create/$',
                self.article_create_view_class.as_view(),
                name='create'),
            url(r'^(?P<path>.+/|)_delete/$',
                self.article_delete_view_class.as_view(),
                name='delete'),
            url(r'^(?P<path>.+/|)_deleted/$',
                self.article_deleted_view_class.as_view(),
                name='deleted'),
            url(r'^(?P<path>.+/|)_edit/$',
                self.article_edit_view_class.as_view(),
                name='edit'),
            url(r'^(?P<path>.+/|)_move/$',
                self.article_move_view_class.as_view(),
                name='move'),
            url(r'^(?P<path>.+/|)_preview/$',
                self.article_preview_view_class.as_view(),
                name='preview'),
            url(r'^(?P<path>.+/|)_history/$',
                self.article_history_view_class.as_view(),
                name='history'),
            url(r'^(?P<path>.+/|)_dir/$',
                self.article_dir_view_class.as_view(),
                name='dir'),
            url(r'^(?P<path>.+/|)_search/$',
                get_class_from_str(self.search_view_class).as_view(),
                name='search'),
            url(r'^(?P<path>.+/|)_settings/$',
                self.article_settings_view_class.as_view(),
                name='settings'),
            url(r'^(?P<path>.+/|)_source/$',
                self.article_source_view_class.as_view(),
                name='source'),
            url(
                r'^(?P<path>.+/|)_revision/change/(?P<revision_id>[0-9]+)/$',
                self.revision_change_view_class.as_view(),
                name='change_revision'),
            url(
                r'^(?P<path>.+/|)_revision/merge/(?P<revision_id>[0-9]+)/$',
                self.revision_merge_view,
                name='merge_revision'),
            url(r'^(?P<path>.+/|)_plugin/(?P<slug>\w+)/$',
                self.article_plugin_view_class.as_view(),
                name='plugin'),
            # This should always go last!
            url(r'^(?P<path>.+/|)$',
                self.article_view_class.as_view(),
                name='get'),
        ]
        return urlpatterns

    @staticmethod
    def get_plugin_urls():
        urlpatterns = []
        for plugin in registry.get_plugins().values():
            slug = getattr(plugin, 'slug', None)
            if slug:
                article_urlpatterns = plugin.urlpatterns.get('article', [])
                urlpatterns += [
                    url(r'^(?P<article_id>[0-9]+)/plugin/' + slug + '/',
                        include(article_urlpatterns)),
                    url(r'^(?P<path>.+/|)_plugin/' + slug + '/',
                        include(article_urlpatterns)),
                ]
                root_urlpatterns = plugin.urlpatterns.get('root', [])
                urlpatterns += [
                    url(r'^_plugin/' + slug + '/', include(root_urlpatterns)),
                ]
        return urlpatterns


def get_pattern(app_name="wiki", namespace="wiki", url_config_class=None):
    """Every url resolution takes place as "wiki:view_name".
       You should not attempt to have multiple deployments of the wiki in a
       single Django project.

wiki/templates/wiki/includes/anonymous_blocked.html
{% load i18n %}

<em>
{% url 'wiki:signup' as signup_url %}
{% url 'wiki:login' as login_url %}
{% if login_url and signup_url %}
  {% blocktrans %}
  You need to <a href="{{ login_url }}">log in</a> or <a href="{{ signup_url }}">sign up</a> to use this function.
  {% endblocktrans %}
{% else %}
  {% trans "You need to log in or sign up to use this function." %}
{% endif %}
</em>

wiki/templates/wiki/includes/article_menu.html
{% load i18n wiki_tags %}

{% with selected_tab as selected %}

<li class="pull-right{% if selected == "settings" %} active{% endif %}">
  {% if not user.is_anonymous %}
  <a href="{% url 'wiki:settings' article_id=article.id path=urlpath.path %}">
    <span class="fa fa-wrench"></span>
    <span class="hidden-xs">{% trans "Settings" %}</span>
  </a>
  {% endif %}
</li>

{% for plugin in article_tabs %}
  <li class="pull-right{% if selected == plugin.slug %} active{% endif %}">
    <a href="{% url 'wiki:plugin' slug=plugin.slug article_id=article.id path=urlpath.path %}">
      <span class="{{ plugin.article_tab.1 }}"></span>
      <span class="hidden-xs">{{ plugin.article_tab.0 }}</span>
    </a>
  </li>
{% endfor %}

<li class="pull-right{% if selected == "history" %} active{% endif %}">
  <a href="{% url 'wiki:history' article_id=article.id path=urlpath.path %}">
    <span class="fa fa-clock-o"></span>
    <span class="hidden-xs">{% trans "Changes" %}</span>
  </a>
</li>

{% if article|can_write:user and not article.current_revision.locked %}
<li class="pull-right{% if selected == "edit" %} active{% endif %}">
  <a href="{% url 'wiki:edit' article_id=article.id path=urlpath.path %}">
    <span class="fa fa-edit"></span>
    <span class="hidden-xs">{% trans "Edit" %}</span>
  </a>
</li>
{% else %}
<li class="pull-right{% if selected == "source" %} active{% endif %}">
  <a href="{% url 'wiki:source' article_id=article.id path=urlpath.path %}">
    <span class="fa fa-lock"></span>
    <span class="hidden-xs">{% trans "View Source" %}</span>
  </a>
</li>
{% endif %}

<li class="pull-right{% if selected == "view" %} active{% endif %}">
  <a href="{% url 'wiki:get' article_id=article.id path=urlpath.path %}">
    <span class="fa fa-home"></span>
    <span class="hidden-xs">{% trans "View" %}</span>
  </a>
</li>

{% endwith %}

wiki/templates/wiki/includes/breadcrumbs.html
{% load i18n %}
{% if urlpath %}
<div id="article-breadcrumbs">

<ul class="breadcrumb pull-left">
  {% for ancestor in urlpath.cached_ancestors %}
    <li><a href="{% url 'wiki:get' path=ancestor.path %}">{{ ancestor.article.current_revision.title|truncatechars:25 }}</a></li>
  {% endfor %}
  <li class="active">{{ article.current_revision.title|truncatechars:25 }}</li>
</ul>
<div class="pull-left" style="margin-left: 10px;">
  <div class="btn-group">
    <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#" style="padding: 7px;" title="{% trans "Sub-articles for" %} {{ article.current_revision.title }}">
      <span class="fa fa-sitemap"></span>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      {% for child in children_slice %}
        <li>
          <a href="{% url 'wiki:get' path=child.path %}">
            {{ child.article.current_revision.title }}
          </a>
        </li>
        {% empty %}
        <li><a href="#"><em>{% trans "No sub-articles" %}</em></a></li>
      {% endfor %}
      {% if children_slice_more %}
      <li><a href="#"><em>{% trans "...and more" %}</em></a></li>
      {% endif %}
      <li class="divider"></li>
      <li>
        <a href="{% url 'wiki:dir' path=urlpath.path %}">{% trans "Browse articles in this level" %} &raquo;</a>
      </li>
    </ul>
  </div>
</div>
<div class="pull-left" style="margin-left: 10px;">
  <div class="btn-group">
    <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#" style="padding: 7px;" title="{% trans "Sub-articles for" %} {{ article.current_revision.title }}">
      <span class="fa fa-file"></span>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
        {% if urlpath.parent %}
        <a href="{% url 'wiki:create' path=urlpath.parent.path %}" style="padding: 7px;">
          <span class="fa fa-arrow-right"></span>
          {% blocktrans with article.current_revision.title as title %}New article next to {{ title }}{% endblocktrans %}
        </a>
        {% endif %}
        <a href="{% url 'wiki:create' path=urlpath.path %}" style="padding: 7px;">
          <span class="fa fa-arrow-down"></span>
          {% blocktrans with article.current_revision.title as title %}New article below {{ title }}{% endblocktrans %}
        </a>
      </li>
    </ul>
  </div>
</div>
<div style="clear: both"></div>
</div>
{% endif %}

wiki/templates/wiki/includes/editor.html
{% load wiki_tags i18n sekizai_tags %}
{% include "wiki/includes/editormedia.html" %}

{% wiki_form form %}
{% addtoblock "js" %}
<script language="javascript">
  $(document).ready(function() {
    $("#id_revision").val('{{ article.current_revision.id }}');
  });
</script>
{% endaddtoblock %}

wiki/templates/wiki/includes/editor_sidebar.html
{% load i18n sekizai_tags %}
{% addtoblock "js" %}
<script type="text/javascript">
  $(document).ready( function() {
    $('.sidebar-form').each(function () {
      $(this).submit( function() {
        this.unsaved_article_title.value = $('#id_title').val();
        this.unsaved_article_content.value = $('#id_content').val();
      });
    });
  });
</script>
{% endaddtoblock %}

<div class="panel-group" id="accordion_{{ plugin.slug }}">

{% for plugin, plugin_form in sidebar %}

  <div class="panel panel-default">

    <div class="panel-heading">
      <a class="panel-toggle" href="#collapse_{{ plugin.slug }}" data-toggle="collapse">
        <h3 class="panel-title"><span class="fa fa-fw {{ plugin.sidebar.icon_class }}"></span> {{ plugin.sidebar.headline }}</h3>
      </a>
    </div>

    <div id="collapse_{{ plugin.slug }}" class="panel-collapse collapse{% if plugin_form.errors %} in{% endif %}">
      <div class="panel-body form-vertical">
        {% if plugin.sidebar.template %}
          {% with plugin_form as form and plugin as plugin %}
            <form method="POST" class="form-horizontal sidebar-form" action="?f={{ plugin_form.form_id }}" enctype="multipart/form-data">
              {% csrf_token %}
              {% include plugin.sidebar.template %}
            </form>
          {% endwith %}
        {% endif %}
      </div>
    </div>

  </div>
{% endfor %}
</div>

wiki/templates/wiki/includes/editormedia.html
{% load sekizai_tags static %}
{% addtoblock "js" %}
<script type="text/javascript" src="{% static "wiki/js/editor.js" %}"></script>
{% for js in editor.Media.js %}
<script type="text/javascript" src="{% static js %}"></script>
{% endfor %}
{% endaddtoblock %}

{% addtoblock "css" %}
{% for media, srcs in editor.Media.css.items %}
  {% for src in srcs %}
    <link rel="stylesheet" media="{{ media }}" href="{% static src %}" />
  {% endfor %}
{% endfor %}
{% endaddtoblock %}

wiki/templates/wiki/includes/form.html
{% csrf_token %}{% load sekizai_tags %}

{% include "wiki/includes/formerrors.html" %}

{% addtoblock "js" %}
{{ form.media.js }}
{% endaddtoblock %}

{% addtoblock "css" %}
{{ form.media.css }}
{% endaddtoblock %}

{% for field in form %}

  {% include "wiki/includes/formfield.html" %}

{% endfor %}

wiki/templates/wiki/includes/formfield.html
{% if field.is_hidden %}
  {{ field }}
{% else %}

<div id="div_{{ field.auto_id }}" class="form-group{% if field.errors %} has-error{% endif %}">
  <div class="wiki-label col-xs-3 col-lg-2">
  {% if field.label %}
    <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
    {{ field.label|safe }}
    </label>
  {% endif %}
  </div>
  <div class="wiki-control col-xs-9 col-lg-10">
    {{ field }} {% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
    {% if field.errors %}
      {% for error in field.errors %}
        <div id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="help-block"><strong>{{ error }}</strong></div>
      {% endfor %}
    {% endif %}
    {% if field.help_text %}
      <p id="hint_{{ field.auto_id }}" class="help-block">{{ field.help_text|safe }}</p>
    {% endif %}
  </div>
</div>
{% endif %}

wiki/templates/wiki/includes/messages.html
{% if messages %}
  <!-- Messages for this instance -->
  {% for message in messages %}
    <div class="{{ message.css_class }}">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

wiki/templates/wiki/includes/modals.html
{% load sekizai_tags static %}
{% addtoblock "js" %}
<script type="text/javascript" src="{% static "wiki/js/jqueryui/jquery-ui-1.10.0.custom.min.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
  $(".modal-content").on("resizestart", function(event, ui) {
    $(ui.element).find(".modal-body, iframe").each(function() {
      elem = $(this);
      elem.data("resizeoriginalheight", elem.height());
    });
  });

  $(".modal-content").on("resize", function(event, ui) {
      ui.element.parents('.modal-dialog').css("margin-left", -ui.size.width/2);
      ui.element.parents('.modal-dialog').css("margin-top", -ui.size.height/2);
      ui.element.parents('.modal-dialog').css("top", "50%");
      ui.element.parents('.modal-dialog').css("left", "50%");

      $(ui.element).find(".modal-body,iframe").each(function() {
        elem = $(this);
        $(this).css("min-height", elem.data("resizeoriginalheight") + ui.size.height - ui.originalSize.height);
      });
  });

  $(".modal-content").resizable();
});
</script>
{% endaddtoblock %}
{% addtoblock "css" %}
<link rel="stylesheet" href="{% static "wiki/js/jqueryui/jquery-ui-1.10.0.custom.min.css" %}" type="text/css" />
{% endaddtoblock %}

wiki/templates/wiki/includes/move_tree.html
{% load wiki_tags %}

<li class="{% if current_path.path|starts_with:urlpath.path %}disabled{% endif%} {% if current_path.children.count %}dropdown-submenu{% endif %}">
  <a tabindex="-1" href="#"
    {% if not current_path.path|starts_with:urlpath.path %}
        onclick="select_path('{{current_path.pk}}', '{{current_path.path|escapejs}}');" {% endif %}>
    {{current_path.article}}
  </a>
  {% if current_path.children.count %}
    <ul class="dropdown-menu">
      {% for current_path in current_path.get_ordered_children %}
        {% with template_name="wiki/includes/move_tree.html" %}{% include template_name %}{% endwith %}
      {% endfor %}
    </ul>
  {% endif %}
</li>

wiki/templates/wiki/includes/pagination.html
{% load i18n %}
{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li><a class="prev btn btn-info" href="?{% if search_query %}q={{ search_query  }}&{% endif %}page={{ page_obj.previous_page_number }}{% if appended_key %}&{{ appended_key }}={{ appended_value }}{% endif %}">&laquo;</a></li>
    {% else %}
        <li class="disabled"><span>&laquo;</span></li>
    {% endif %}

    {% for pc in paginator.page_range %}
        {% if pc == 0 %}
            <li class="disabled"><span>...</span></li>
        {% else %}
            <li class="{% if pc == page_obj.number %} active{% endif %}"><a href="?{% if search_query %}q={{ search_query  }}&{% endif %}page={{ pc }}{% if appended_key %}&{{ appended_key }}={{ appended_value }}{% endif %}">{{ pc }}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li><a class="next btn btn-info" href="?{% if search_query %}q={{ search_query  }}&{% endif %}page={{ page_obj.next_page_number }}{% if appended_key %}&{{ appended_key }}={{ appended_value }}{% endif %}">&raquo;</a></li>
    {% else %}
        <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}

wiki/templates/wiki/includes/revision_info.html
{% comment %}

  This reusable code is shared between different templates and different inheritors of
  BaseRevision.

{% endcomment %}


{% load wiki_tags i18n %}
{% if not hidedate %}{{ revision.created }}{% endif %} {% if not hidenumber %}(#{{ revision.revision_number }}) {% trans "by" %}{% endif %} {% if revision.user %}{{ revision.user }}{% else %}{% if article|can_moderate:user %}{{ revision.ip_address|default:"anonymous (IP not logged)" }}{% else %}{% trans "anonymous (IP logged)" %}{% endif %}{% endif %}
{% if revision == current_revision %}
  <strong>*</strong>
{% endif %}
{% if revision.deleted %}
<span class="badge badge-important">{% trans "deleted" %}</span>
{% endif %}
{% if revision.previous_revision.deleted and not revision.deleted %}
<span class="badge badge-success">{% trans "restored" %}</span>
{% endif %}
{% if revision.locked %}
<span class="badge">{% trans "locked" %}</span>
{% endif %}
{% if revision.previous_revision.locked and not revision.locked %}
<span class="badge">{% trans "unlocked" %}</span>
{% endif %}

wiki/templates/wiki/includes/searchresult.html
{% load wiki_tags i18n humanize %}


<tr>
  <td>
    {% for urlpath in article.urlpath_set.all %}
      <a href="{% url 'wiki:get' path=urlpath.path %}">{{ article.current_revision.title }}<br /><small class="muted">/{{ urlpath.path }}</small></a>
    {% empty %}
      <a href="{% url 'wiki:get' article_id=article.id %}">{{ article.current_revision.title }}</a>
    {% endfor %}
    {% if article.current_revision.deleted %}
      <span class="fa fa-trash"></span>
    {% endif %}
    {% if article.current_revision.locked %}
      <span class="fa fa-lock"></span>
    {% endif %}
    <p class="muted"><small>{{ article.render|get_content_snippet:search_query }}</small></p>
  </td>
  <td style="white-space: nowrap">
    {{ article.current_revision.created|naturaltime }}
  </td>
</tr>